// src/context/LangContext.jsx

import React, { createContext, useContext, useState, useEffect } from 'react';

// Translation dictionary
const translations = {
  ua: {
    home: 'Головна',
    search: 'Пошук',
    account: 'Кабінет',
    login: 'Вхід',
    register: 'Реєстрація',
    features: 'Наші переваги',
    partners: 'Наші партнери',
    testimonials: 'Відгуки клієнтів',
    support: 'Підтримка',
    seats_left: 'місць',
    book_now: 'Забронювати',
    passenger_details: 'Деталі пасажира:',
    confirm: 'Підтвердити',
    available_routes: 'Доступні рейси',
    Failed_to_load_routes: 'Не вдалося завантажити рейси',
    no_routes_found_for_your_search: 'Рейсів не знайдено',
    Failed_to_book_ticket: 'Не вдалося забронювати квиток',
    Your_tickets: 'Мої квитки',
    Failed_to_load_tickets: 'Не вдалося завантажити квитки',
    No_tickets_purchased_yet: 'Ще немає квитків',
    download: 'Завантажити',
    cancel: 'Скасувати',
    ticket_info: 'Інформація про квиток',
    back: 'Назад',
    ticket_not_found: 'Квиток не знайдено',
    Email: 'Email',
    Password: 'Пароль',
    Invalid_credentials: 'Невірні дані',
    Full_Name: 'ПІБ',
    Email_Address: 'Email',
    Enter_email: 'Введіть email',
    Enter_password: 'Введіть пароль',
    No_account: 'Немає акаунту?',
    registration_success: 'Реєстрація успішна! Переадресація...',
    Registration_failed: 'Реєстрація не вдалася. Спробуйте ще.',
    Already_have_an_account: 'Вже є акаунт?',
    passenger: 'Пасажир',
    operator: 'Перевізник',
    Route: 'Маршрут',
    Price: 'Ціна',
    Departure: 'Відправлення',
    Phone: 'Телефон',
    popular_routes: 'Популярні маршрути',
    loading: 'Завантаження...',
    about_us: 'Про нас',
    about_description_1: 'BusTickets — це інноваційний сервіс з продажу автобусних квитків по всій Україні. Наша місія — зробити подорожі швидкими, зручними та доступними для кожного.',
    about_description_2: 'Ми об’єднали найкращі автобусні перевезення, щоб ви могли порівняти ціни, обрати комфортні рейси та придбати квитки онлайн за лічені хвилини.',
    feature_routes: 'Понад 1000 напрямків',
    feature_easy_booking: 'Легке бронювання за 3 кліки',
    feature_pdf: 'Миттєва генерація PDF-квитка',
    privacy_policy: 'Політика конфіденційності',
    privacy_description: 'Ми цінуємо вашу конфіденційність і докладаємо максимум зусиль для захисту ваших персональних даних.',
    privacy_point_1: 'Ми не зберігаємо зайвої інформації — лише те, що потрібно для покупки квитків.',
    privacy_point_2: 'Уся інформація зберігається в безпечному середовищі й не передається стороннім без вашої згоди.',
    privacy_extra: 'Якщо у вас виникли запитання щодо обробки ваших персональних даних — зверніться до служби підтримки.',
    We_understand_how_important: 'Ми розуміємо, наскільки важливо зберігати ваші персональні дані в безпеці. Ця політика конфіденційності пояснює, як ми збираємо, зберігаємо та використовуємо вашу інформацію при взаємодії з нашим сайтом.',
    Our_platform_is_built: 'Наша платформа побудована з урахуванням конфіденційності. Від шифрованих зʼєднань до захищених баз даних — ми робимо все можливе, щоб захистити ваші дані.',
    terms_title: 'Умови обслуговування',
    terms_subtitle: 'Будь ласка, уважно ознайомтесь перед використанням сайту.',
    terms_intro: 'Використовуючи наш сервіс, ви підтверджуєте, що ознайомлені та погоджуєтесь з наступними умовами:',
    terms_rule_1: 'Квитки не підлягають поверненню після відправлення автобуса.',
    terms_rule_2: 'Ми не несемо відповідальності за затримки, спричинені форс-мажорами.',
    blog_title: 'Блог — Наші статті',
    careers_title: 'Кар’єра в BusTickets',
    careers_intro: 'Приєднуйтесь до нашої дружньої команди! Ми шукаємо талановитих фахівців у таких напрямках:',
    careers_contact: 'Надсилайте резюме на',
    faq_title: 'Часті запитання',
    faq_subtitle: 'Ми зібрали відповіді на найпоширеніші питання користувачів.',
    faq_q1: 'Як забронювати квиток?',
    faq_a1: 'На головній сторінці введіть «Звідки», «Куди», дату і кількість пасажирів → натисніть «Пошук» → оберіть рейс → введіть дані пасажирів → «Підтвердити».',
    faq_q2: 'Як завантажити PDF-квиток?',
    faq_a2: 'Після бронювання перейдіть до «Кабінет» → знайдіть потрібний квиток → натисніть «Завантажити PDF».',
    faq_q3: 'Як скасувати квиток?',
    faq_a3: 'В особистому кабінеті поруч із квитком натисніть «Скасувати квиток» і підтвердіть.',
    faq_q4: 'Чи потрібно реєструватися для пошуку рейсу?',
    faq_a4: 'Ні, пошук рейсів та перегляд спецпропозицій доступні без авторизації.',
    your_tickets: 'Ваші квитки:',
    available_routes: 'Доступні маршрути:',
    no_routes_found: 'Маршрутів за вашим запитом не знайдено',
    seats_left: 'вільних місць',
    book_now: 'Забронювати',
    personal_account: "Особистий акаунт",
    Support: 'Підтримка',
  'If you have questions, call': 'Якщо у вас виникли питання — зателефонуйте',
  'You can also send us a message and we will get back to you.': 'Або надішліть повідомлення, і ми вам відповімо.',
    Name: 'Імʼя',
    Email: 'Електронна пошта',
    Message: 'Повідомлення',
    Send: 'Надіслати',
  'Your message was successfully sent!': 'Ваше повідомлення успішно надіслано!',
    ticket_info: 'Інформація про квиток',
    ticket_not_found: 'Квиток не знайдено',
    route: 'Маршрут',
    date: 'Дата',
    operator: 'Перевізник',
    passenger: 'Пасажир',
    phone: 'Телефон',
    price: 'Ціна',
    payment_on_board: 'Оплата при посадці',
    ticket_number: 'Квиток №',
    download: 'Завантажити',
  },
  en: {
    home: 'Home',
    search: 'Search',
    account: 'Account',
    login: 'Login',
    register: 'Register',
    features: 'Our Features',
    partners: 'Our Partners',
    testimonials: 'Testimonials',
    support: 'Support',
    seats_left: 'seats left',
    book_now: 'Book Now',
    passenger_details: 'Passenger Details:',
    confirm: 'Confirm',
    available_routes: 'Available Routes',
    Failed_to_load_routes: 'Failed to load routes',
    no_routes_found_for_your_search: 'No routes found',
    Failed_to_book_ticket: 'Failed to book ticket',
    Your_tickets: 'Your Tickets',
    Failed_to_load_tickets: 'Failed to load tickets',
    No_tickets_purchased_yet: 'No tickets purchased yet!',
    download: 'Download',
    cancel: 'Cancel',
    ticket_info: 'Ticket Information',
    back: 'Back',
    ticket_not_found: 'Ticket not found',
    Email: 'Email',
    Password: 'Password',
    Invalid_credentials: 'Invalid credentials',
    Full_Name: 'Full Name',
    Email_Address: 'Email Address',
    Enter_email: 'Enter email address',
    Enter_password: 'Enter password',
    No_account: 'No account?',
    registration_success: 'Registration successful! Redirecting...',
    Registration_failed: 'Registration failed. Try again.',
    Already_have_an_account: 'Already have an account?',
    passenger: 'Passenger',
    operator: 'Operator',
    Route: 'Route',
    Price: 'Price',
    Departure: 'Departure',
    Phone: 'Phone',
    popular_routes: 'Popular Routes',
    loading: 'Loading...',
    about_us: 'About Us',
    about_description_1: 'BusTickets is an innovative service for buying bus tickets across Ukraine. Our mission is to make travel fast, convenient, and accessible for everyone.',
    about_description_2: 'We combined top bus carriers so you can compare prices, choose comfortable routes, and buy tickets online in just a few clicks.',
    feature_routes: 'Over 1000 destinations',
    feature_easy_booking: 'Easy booking in 3 clicks',
    feature_pdf: 'Instant PDF ticket generation',
    privacy_policy: 'Privacy Policy',
    privacy_description: 'We value your privacy and take every measure to protect your personal data.',
    privacy_point_1: 'We do not store unnecessary data — only what is needed for booking tickets.',
    privacy_point_2: 'All data is stored securely and never shared without your consent.',
    privacy_extra: 'If you have any questions about how we handle your personal data, feel free to contact our support team.',
    We_understand_how_important: 'We understand how important it is to keep your personal data private. This privacy policy outlines how we collect, store, and use your data when you interact with our website.',
    Our_platform_is_built: 'Our platform is built with privacy in mind. From encrypted connections to secure databases, we take steps to protect your information.',
    terms_title: 'Terms of Service',
    terms_subtitle: 'Please read carefully before using the website.',
    terms_intro: 'By using our service, you confirm that you have read and agree to the following terms:',
    terms_rule_1: 'Tickets are non-refundable after the bus has departed.',
    terms_rule_2: 'We are not responsible for delays caused by force majeure circumstances.',
    blog_title: 'Blog — Our Articles',
    careers_title: 'Careers at BusTickets',
    careers_intro: 'Join our friendly team! We are looking for talented professionals in the following areas:',
    careers_contact: 'Send your CV to',
    faq_title: 'Frequently Asked Questions',
    faq_subtitle: 'We’ve gathered answers to the most common user questions.',
    faq_q1: 'How do I book a ticket?',
    faq_a1: 'On the homepage, enter "From", "To", date, and number of passengers → click "Search" → select a trip → enter passenger info → click "Confirm".',
    faq_q2: 'How to download a PDF ticket?',
    faq_a2: 'After booking, go to "Account" → find your ticket → click "Download PDF".',
    faq_q3: 'How can I cancel my ticket?',
    faq_a3: 'In your personal account, next to the ticket, click "Cancel Ticket" and confirm.',
    faq_q4: 'Do I need to register to search routes?',
    faq_a4: 'No, route search and special offers are available without logging in.',
    your_tickets: 'Your Tickets:',
    available_routes: 'Available Routes:',
    no_routes_found: 'No routes found for your search',
    seats_left: 'seats left',
    book_now: 'Book Now',
    personal_account: "Personal account",
    Support: 'Support',
  'If you have questions, call': 'If you have questions, call',
  'You can also send us a message and we will get back to you.': 'You can also send us a message and we will get back to you.',
    Name: 'Name',
    Email: 'Email',
    Message: 'Message',
    Send: 'Send',
  'Your message was successfully sent!': 'Your message was successfully sent!',
    ticket_info: 'Ticket Information',
    ticket_not_found: 'Ticket not found',
    route: 'Route',
    date: 'Date',
    operator: 'Operator',
    passenger: 'Passenger',
    phone: 'Phone',
    price: 'Price',
    payment_on_board: 'Pay on board',
    ticket_number: 'Ticket No.',
    download: 'Download',
  }
};

const LangContext = createContext();

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState(
    () => localStorage.getItem('lang') || 'ua'
  );

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const toggle = () => setLang(prev => (prev === 'ua' ? 'en' : 'ua'));

  const L = key => translations[lang][key] || key;

  return (
    <LangContext.Provider value={{ lang, toggle, L }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);
